version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tcc
      MYSQL_USER: user_database
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  nginx:
    container_name: nginx
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    depends_on:
      - db

  php:
    container_name: php
    build: images/php
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html/app
    command: php-fpm
    links:
      - db:db
    ports:
      - "8000:8000"
    depends_on:
      - db